apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins
  namespace: jenkinsdev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: jenkins/jenkins
        ports:
        - containerPort: 8080
        volumeMounts:
              - name: persistent-storage
                mountPath: /tmp/jenkins_home
      volumes:
      - name: persistent-storage
        persistentVolumeClaim:
           claimName: jenkins-data
